### PR TITLE
[network] Implement method to see if vif connected

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1011

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/754

**Comment by jean-edouard** [comment]
Code LGTM, I mean it's awful but it matches the rest of the program :)
+1

**Comment by crogers1** [comment]
That's what we call "Meets Expectations"

**Comment by crogers1** [comment]
Updated with a small diff to update the wireless network name.  Everywhere else on the platform, we're using '/wifi/'  instead of '/wireless/' to denote a wireless network.  Networkdaemon and xenmgr were the last two places that needed to be updated (see the M_13.hs migration script).  When '/wifi/0/shared' comes down from the toolstack, networkdaemon should know that it's a wireless network and handle it appropriately.

**Pull request merged**
